### ISSUE TITLE
The wrong README.md is displayed on the repository root.

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/github-apps-config-next#13]
https://github.com/Financial-Times/github-apps-config-next incorrectly displays the README.md that is in the `.github` directory.

I expect it to show this README.md: https://github.com/Financial-Times/github-apps-config-next/blob/master/README.md

**Comment by sjparkinson** [comment]
Ah, https://help.github.com/articles/about-readmes/.

I'm going to assume they load from `.github/README.md` before looking at the root of a repository.

That's kinda surprising. Worth raising it as an issue with GitHub, I'd expect it to be the other way around.

**Comment by adambraimbridge** [comment]
> Worth raising it as an issue with GitHub
Will do.
