### ISSUE TITLE
Settings GitHub app turns off 'Automatically delete head branches' option

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/github-apps-config-next#19]
This is a known issue, although the GitHub issue doesn't mention that it will turn the option off if it is already enabled: https://github.com/probot/settings/issues/134

**Comment by simonplend** [comment]
I've confirmed that the GitHub REST API v3 doesn't currently support the 'Automatically delete head branches' option: https://developer.github.com/v3/repos/#edit

When the GitHub API supports that option we'll need to wait for [`@octokit/rest`](https://octokit.github.io/rest.js/#octokit-routes-repos-update) to support it, and then for the [GitHub Settings app](https://github.com/probot/settings) to use the new version of `@octokit/rest`.

**Comment by sjparkinson** [comment]
What I don't understand is how and why it can be modifying the setting if there isn't an API for it!?

**Comment by sjparkinson** [comment]
There also isn't a good track record for GitHub to add these new settings as an editable via the API.

e.g. "Restrict editing to users in teams with push access only" has been around forever, but there is still no field in the API to edit it.

**Comment by localheinz** [comment]
@simonplend 

See https://github.com/probot/settings/issues/134#issuecomment-572804489.
