### ISSUE TITLE
Document GitHub Apps that we use in the README

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/github-apps-config-next#3]
In [the README](/Financial-Times/github-apps-config-next/blob/master/README.md), explain what we use each GitHub App for.

**Comment by adambraimbridge** [comment]
Reopening this because https://github.com/Financial-Times/github-apps-config-next/issues/13

**Comment by adambraimbridge** [comment]
Bump

**Comment by simonplend** [comment]
@adambraimbridge Why bump? It looks like the correct README is showing here now: https://github.com/Financial-Times/github-apps-config-next

**Comment by adambraimbridge** [comment]
I get anxiety about stalebot closing things automatically, and wanted to check it's done before it closes. Bumping it puts it off so I don't have to deal with it right now. 

Yeah, I shouldn't do that.

**Comment by simonplend** [comment]
You are becoming the `antistalebot` :joy:

If an issue is important enough I think it will crop up again - at least that's the theory we've gone with by adding `stalebot` to our repositories.
